language: cpp

sudo: false

os:
  - osx

addons:
  apt:
    sources:
    - ubuntu-toolchain-r-test
    packages:
    - g++-4.8

env:
  matrix:
  - TRAVIS_NODE_VERSION="0.10"
  - TRAVIS_NODE_VERSION="0.12"
  - TRAVIS_NODE_VERSION="4"

matrix:
  allow_failures:
    - fast_finish: true

before_install:
  - if [[ $TRAVIS_OS_NAME == "osx" ]]; then brew install gmp graphicsmagick; fi

install:
  - rm -rf ~/.nvm && git clone https://github.com/creationix/nvm.git ~/.nvm && (cd ~/.nvm && git checkout `git describe --abbrev=0 --tags`) && source ~/.nvm/nvm.sh && nvm install $TRAVIS_NODE_VERSION
  - PATH="`npm bin`:`npm bin -g`:$PATH"
  - npm install -g npm@2
  - node --version
  - npm --version

script:
  - if [ $TRAVIS_NODE_VERSION == "4" ]; then export CXX=g++-4.8; fi
  - npm config set spin false
  - npm install
  - export PM2_HOME=".."
  - node_modules/.bin/pm2 ping
  - node_modules/.bin/pm2 kill
  - node_modules/.bin/pm2 start
